'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class clientes
    Public Property id_cliente As Integer
    Public Property apellido As String
    Public Property nombre As String
    Public Property telefono As Nullable(Of Long)
    Public Property fecha_nacimiento As Nullable(Of Date)
    Public Property correo As String
    Public Property direccion As String
    Public Property id_estado_cliente As Integer
    Public Property dni As Nullable(Of Long)

    Public Overridable Property Estados_clientes As Estados_clientes
    Public Overridable Property ventas As ICollection(Of ventas) = New HashSet(Of ventas)

End Class
