'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DetalleVenta
    Public Property id_venta As Integer
    Public Property id_venta_detalle As Integer
    Public Property id_producto As Nullable(Of Integer)
    Public Property cantidad As Nullable(Of Integer)
    Public Property precio As Nullable(Of Decimal)

    Public Overridable Property Productos As Productos
    Public Overridable Property ventas As ventas

End Class
