'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Empleados
    Public Property id_empleado As Integer
    Public Property dni As Integer
    Public Property apellido As String
    Public Property nombre As String
    Public Property direccion As String
    Public Property telefono As String
    Public Property correo As String
    Public Property fecha_nacimiento As Nullable(Of Date)
    Public Property id_sexo As Nullable(Of Integer)
    Public Property id_estado_empleado As Nullable(Of Integer)

    Public Overridable Property Estados_empleados As Estados_empleados
    Public Overridable Property Sexos As Sexos
    Public Overridable Property Usuarios As ICollection(Of Usuarios) = New HashSet(Of Usuarios)

End Class
