'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class Proyecto2023Entities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=Proyecto2023Entities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property Categorias() As DbSet(Of Categorias)
    Public Property clientes() As DbSet(Of clientes)
    Public Property detalle() As DbSet(Of detalle)
    Public Property Empleados() As DbSet(Of Empleados)
    Public Property Estados_clientes() As DbSet(Of Estados_clientes)
    Public Property Estados_empleados() As DbSet(Of Estados_empleados)
    Public Property Estados_productos() As DbSet(Of Estados_productos)
    Public Property Estados_ventas() As DbSet(Of Estados_ventas)
    Public Property Perfiles() As DbSet(Of Perfiles)
    Public Property Productos() As DbSet(Of Productos)
    Public Property Sexos() As DbSet(Of Sexos)
    Public Property tipos_pagos() As DbSet(Of tipos_pagos)
    Public Property Usuarios() As DbSet(Of Usuarios)
    Public Property ventas() As DbSet(Of ventas)

End Class
