'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tipos_pagos
    Public Property id_tipo_pago As Integer
    Public Property descripcion As String

    Public Overridable Property ventas As ICollection(Of ventas) = New HashSet(Of ventas)

End Class
