'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ventas
    Public Property id_venta As Integer
    Public Property id_cliente As Integer
    Public Property id_usuario As Integer
    Public Property total As Nullable(Of Decimal)
    Public Property fecha_compra As Nullable(Of Date)
    Public Property id_estado_venta As Integer
    Public Property id_tipo_pago As Integer

    Public Overridable Property clientes As clientes
    Public Overridable Property detalle As ICollection(Of detalle) = New HashSet(Of detalle)
    Public Overridable Property Estados_ventas As Estados_ventas
    Public Overridable Property tipos_pagos As tipos_pagos
    Public Overridable Property Usuarios As Usuarios

End Class
